### PR TITLE
Fix hostname related fronted issues

### LINKED ISSUE #48: Hostname tab issues
- After each submit of hostnames, the old ones will get assigned new dns_challenges 
- For imported relying party hostnames, DNS check should not be an active tab ( It will be empty). Maybe it can say manually verified.

### PR DESCRIPTION
**Pull request by saravahdatipour**
Fixes #48 
related to #42

### CODE REVIEW

File: portal_frontend/src/components/forms/relying-party/dnscheck.tsx [hunk 1]
```diff
@@ -37,45 +38,45 @@ const DnsChallenges: React.FC<DnsChallengesProps> = ({ hostnames }) => {
...
+                    ) : host.dns_challenge_verified ? (
                       <span className="inline-flex items-center gap-1 text-green-700 bg-green-100 border border-green-300 text-xs px-2 py-1 rounded">
                         Verified
                       </span>
                     ) : host.dns_challenge_invalidated_at ? (
                       <span className="inline-flex items-center gap-1 text-red-700 bg-red-100 border border-red-300 text-xs px-2 py-1 rounded">
                         Invalidated
                       </span>
-                    ) : (
+                    ) : host.dns_challenge ? (
```
Comment (w-ensink) [inline portal_frontend/src/components/forms/relying-party/dnscheck.tsx:64]: Multiple ternaries are a bit hard to read and make the code harder to follow imo. I think a cleaner way would be to add two separate && expressions and remove the null case.

**Review by w-ensink — APPROVED** [review]
